### ISSUE TITLE
supports_index_sort_order? should return false 

### ISSUE THREAD

**Issue by yahonda** [pingcap/activerecord-tidb-adapter#16]
`supports_index_sort_order?` defines if the database supports ascending and descending index.

Currently it returns `true`, however tidb does not support descending index yet then this method should return false until https://github.com/pingcap/tidb/issues/2519 is implemented to TiDB.

Refer https://github.com/rails/rails/pull/28773 for Rails pull request.

**Comment by hooopo** [comment]
Yes, you are right. In the current state, the sort order syntax is compatible with tidb ddl, but it is actually ineffective.

```
my:root@127.0.0.1:4000=> create table a (id bigint primary key, name varchar(255));
my:root@127.0.0.1:4000=> CREATE INDEX idx ON a (name desc);
CREATE INDEX
my:root@127.0.0.1:4000=> show create table a;
 Table | Create Table
-------+-------------------------------------------------------------
 a     | CREATE TABLE "a" (                                         +
       |   "id" bigint(20) NOT NULL,                                +
       |   "name" varchar(255) DEFAULT NULL,                        +
       |   PRIMARY KEY ("id") /*T![clustered_index] CLUSTERED */,   +
       |   KEY "idx" ("name")                                       +
       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

**Comment by yahonda** [comment]
Thanks for the reply. Let me create a pull request to change `supports_index_sort_order?`.

**Comment by yahonda** [comment]
Opened  #17
